apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
  annotations:
    job-hasher: "true"
spec:
  template:
    spec:
      containers:
        - name: example-container
          image: CUSTOM-IMAGE
          command: ["/bin/sh", "-c", "echo hello world"]
          imagePullPolicy: Always
          env:
            - name: FOO
              value: "BAR"
      restartPolicy: Never